### ISSUE TITLE
Broken NPM installation on Windows

### ISSUE THREAD

**Issue by bludnic** [bludnic/opentrader#66]
**Reproduction steps:**

Run `npm i -g opentrader` on Windows.

**Logs:**

```sh
C:\Users\Bludnic\Dev\opentrader> npm i -g opentrader
npm warn cleanup Failed to remove some directories [
npm warn cleanup   [
npm warn cleanup     'C:\\Users\\Bludnic\\AppData\\Roaming\\npm\\node_modules\\opentrader',
npm warn cleanup     [Error: EBUSY: resource busy or locked, rmdir 'C:\Users\Bludnic\AppData\Roaming\npm\node_modules\opentrader'] {
npm warn cleanup       errno: -4082,
npm warn cleanup       code: 'EBUSY',
npm warn cleanup       syscall: 'rmdir',
npm warn cleanup       path: 'C:\\Users\\Bludnic\\AppData\\Roaming\\npm\\node_modules\\opentrader'
npm warn cleanup     }
npm warn cleanup   ],
npm warn cleanup   [
npm warn cleanup     'C:\\Users\\Bludnic\\AppData\\Roaming\\npm\\node_modules\\opentrader',
npm warn cleanup     [Error: EBUSY: resource busy or locked, rmdir 'C:\Users\Bludnic\AppData\Roaming\npm\node_modules\opentrader'] {
npm warn cleanup       errno: -4082,
npm warn cleanup       code: 'EBUSY',
npm warn cleanup       syscall: 'rmdir',
npm warn cleanup       path: 'C:\\Users\\Bludnic\\AppData\\Roaming\\npm\\node_modules\\opentrader'
npm warn cleanup     }
npm warn cleanup   ],
npm warn cleanup   [
npm warn cleanup     'C:\\Users\\Bludnic\\AppData\\Roaming\\npm\\node_modules\\opentrader\\node_modules\\@prisma\\generator-helper',
npm warn cleanup     [Error: EPERM: operation not permitted, rmdir 'C:\Users\Bludnic\AppData\Roaming\npm\node_modules\opentrader\node_modules\@prisma\generator-helper\node_modules'] {
npm warn cleanup       errno: -4048,
npm warn cleanup       code: 'EPERM',
npm warn cleanup       syscall: 'rmdir',
npm warn cleanup       path: 'C:\\Users\\Bludnic\\AppData\\Roaming\\npm\\node_modules\\opentrader\\node_modules\\@prisma\\generator-helper\\node_modules'
npm warn cleanup     }
npm warn cleanup   ],
npm warn cleanup   [
npm warn cleanup     'C:\\Users\\Bludnic\\AppData\\Roaming\\npm\\node_modules\\opentrader\\node_modules',
npm warn cleanup     [Error: EPERM: operation not permitted, rmdir 'C:\Users\Bludnic\AppData\Roaming\npm\node_modules\opentrader\node_modules\ccxt\dist\cjs\src\static_dependencies\starknet\types'] {
npm warn cleanup       errno: -4048,
npm warn cleanup       code: 'EPERM',
npm warn cleanup       syscall: 'rmdir',
npm warn cleanup       path: 'C:\\Users\\Bludnic\\AppData\\Roaming\\npm\\node_modules\\opentrader\\node_modules\\ccxt\\dist\\cjs\\src\\static_dependencies\\starknet\\types'
npm warn cleanup     }
npm warn cleanup   ]
npm warn cleanup ]
npm error code 1
npm error path C:\Users\Bludnic\AppData\Roaming\npm\node_modules\opentrader
npm error command failed
npm error command C:\WINDOWS\system32\cmd.exe /d /s /c node scripts/postinstall.mjs
npm error Prisma schema loaded from schema.prisma
npm error
npm error ✔ Generated Prisma Client (v5.19.1) to .\node_modules\@prisma\client in 203ms
npm error
npm error Start by importing your Prisma Client (See: http://pris.ly/d/importing-client)
npm error
npm error Tip: Want to turn off tips and other hints? https://pris.ly/tip-4-nohints
npm error
npm error Prisma schema loaded from schema.prisma
npm error Datasource "sqlite": SQLite database "dev.db" at "file:C:\Users\Bludnic\.opentrader\dev.db"
npm error
npm error 9 migrations found in prisma/migrations
npm error
npm error Applying migration `20240810180405_add_bot_logs`
npm error Applying migration `20240814143215_add_paper_trading`
npm error Applying migration `20240820113647_merge_base_quote_currency_into_symbol`
npm error Applying migration `20240820150438_add_symbol_and_exchange_account_to_order_table`
npm error Applying migration `20240820174038_bot_with_additional_exchanges_accounts`
npm error Applying migration `20240909034411_bot_add_logging_column`
npm error Applying migration `20241006164140_add_order_relative_price`
npm error
npm error The following migration(s) have been applied:
npm error
npm error migrations/
npm error   └─ 20240810180405_add_bot_logs/
npm error     └─ migration.sql
npm error   └─ 20240814143215_add_paper_trading/
npm error     └─ migration.sql
npm error   └─ 20240820113647_merge_base_quote_currency_into_symbol/
npm error     └─ migration.sql
npm error   └─ 20240820150438_add_symbol_and_exchange_account_to_order_table/
npm error     └─ migration.sql
npm error   └─ 20240820174038_bot_with_additional_exchanges_accounts/
npm error     └─ migration.sql
npm error   └─ 20240909034411_bot_add_logging_column/
npm error     └─ migration.sql
npm error   └─ 20241006164140_add_order_relative_price/
npm error     └─ migration.sql
npm error
npm error All migrations have been successfully applied.
npm error ┌─────────────────────────────────────────────────────────┐
npm error │  Update available 5.19.1 -> 5.21.1                      │
npm error │  Run the following to update                            │
npm error │    npm i -g prisma@latest                               │
npm error │    npm i @prisma/client@latest                          │
npm error └─────────────────────────────────────────────────────────┘
npm error C:\Users\Bludnic\AppData\Roaming\npm\node_modules\opentrader\node_modules\.prisma\client\default.js:43
npm error     throw new Error('@prisma/client did not initialize yet. Please run "prisma generate" and try to import it again.');
npm error           ^
npm error
npm error Error: @prisma/client did not initialize yet. Please run "prisma generate" and try to import it again.
npm error     at new PrismaClient (C:\Users\Bludnic\AppData\Roaming\npm\node_modules\opentrader\node_modules\.prisma\client\default.js:43:11)
npm error     at file:///C:/Users/Bludnic/AppData/Roaming/npm/node_modules/opentrader/seed.mjs:20:16
npm error     at ModuleJob.run (node:internal/modules/esm/module_job:222:25)
npm error     at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
npm error     at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:123:5)
npm error
npm error Node.js v20.16.0
npm error node:internal/errors:984
npm error   const err = new Error(message);
npm error               ^
npm error
npm error Error: Command failed: node seed.mjs
npm error     at genericNodeError (node:internal/errors:984:15)
npm error     at wrappedFn (node:internal/errors:538:14)
npm error     at checkExecSyncError (node:child_process:890:11)
npm error     at execSync (node:child_process:962:15)
npm error     at runMigrations (file:///C:/Users/Bludnic/AppData/Roaming/npm/node_modules/opentrader/scripts/postinstall.mjs:23:5)
npm error     at file:///C:/Users/Bludnic/AppData/Roaming/npm/node_modules/opentrader/scripts/postinstall.mjs:65:1
npm error     at ModuleJob.run (node:internal/modules/esm/module_job:222:25)
npm error     at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
npm error     at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:123:5) {
npm error   status: 1,
npm error   signal: null,
npm error   output: [ null, null, null ],
npm error   pid: 8132,
npm error   stdout: null,
npm error   stderr: null
npm error }
npm error
npm error Node.js v20.16.0
npm error A complete log of this run can be found in: C:\Users\Bludnic\AppData\Local\npm-cache\_logs\2024-10-22T23_03_08_605Z-debug-0.log
```

**Comment by bludnic** [comment]
Ensure you are running PowerShell as an administrator

1. Clear npm cache:

```
npm cache clean --force
```

2. Delete the old installation manually

```
Remove-Item -Path "C:\Users\Bludnic\AppData\Roaming\npm\node_modules\opentrader\*" -Recurse -Force
npm uninstall opentrader -g
```

3. Install it again

```
npm i -g opentrader
opentrader up
```

That solved the issue.
